# This file is used for automated tests with Travis CI : travis-ci.org
# based on the template version 1
# the templates are availables in the documentation on http://docs.domogik.org/domogik/dev/en/package_development/plugins/tests/travis_templates.html
# sudo: false
language: python
python:
  - "2.7"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
env:
  DMG_BRANCH=testcase_non_xpl
  DMG_PLUGIN=ozwave
install:
  - cd ~
  - git clone https://github.com/Nico0084/domogik.git
  - cd domogik
  - git checkout $DMG_BRANCH
  - ~/domogik/src/domogik/tests/travis/travis-install-dependencies.sh
before_script:
  - ~/domogik/src/domogik/tests/travis/travis-setup-database.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-domogik-mq.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-domogik.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-plugin.sh
  - echo "==== Install zwave emulator dependency"
  - cd ~
  - sudo apt-get install socat
  - git clone https://github.com/Nico0084/py-zwave-emulator.git
  - echo "==== Install Plugin dependency"
  - cd $TRAVIS_BUILD_DIR
  - sudo ./install_dependencies.sh -LAST
  - echo "==== Start zwave emulator"
  - cd ~/py-zwave-emulator/bin
  - python zwemulator.py &
  - sudo ~/domogik/src/domogik/tests/travis/travis-start-domogik.sh
script:
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR
  - export PYTHONPATH=/var/lib/domogik
  - dmg_testrunner -a /var/lib/domogik/domogik_packages/plugin_$DMG_PLUGIN/tests/
after_script:
  - ~/domogik/src/domogik/tests/travis/travis-after.sh
  - echo "********** ZWave-emulator log *******************"
  - cat ~/py-zwave-emulator/bin/test.log
  - echo "********** Openzwave lib log *******************"
  - cat $TRAVIS_BUILD_DIR/data/OZW_Log.txt

notifications:
  irc: "irc.freenode.net#domogik"
  on_success: never
  on_failure: never
