# This file is used for automated tests with Travis CI : travis-ci.org
# based on the template version 1
# the templates are availables in the documentation on http://docs.domogik.org/domogik/dev/en/package_development/plugins/tests/travis_templates.html
# sudo: false
sudo: required
#dist: trusty
language: python
python:
  - "2.7"
mysql:
  adapter: mysql2
  database: domogik
  username: travis
  encoding: utf8
env:
  DMG_BRANCH=develop
  DMG_PLUGIN=ozwave
#  VIRTUALENV=/home/travis/virtualenv/python2.7.10
install:
  - cd ~
  - git clone https://github.com/domogik/domogik.git
  - cd domogik
  - git checkout $DMG_BRANCH
  - ~/domogik/src/domogik/tests/travis/travis-install-dependencies.sh
before_script:
#  - ~/domogik/src/domogik/tests/travis/travis_trusty-setup-database.sh
  - ~/domogik/src/domogik/tests/travis/travis-setup-database.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-domogik-mq.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-domogik.sh
  - ~/domogik/src/domogik/tests/travis/travis-install-plugin.sh
  - cd ~
  - echo "==== Install zwave emulator dependency"
  - sudo apt-get install socat
  - git clone https://github.com/Nico0084/py-zwave-emulator.git
  - echo "==== Install Plugin dependency python-openzwave lib"
  - ls -l /var/lib/domogik/domogik_packages/plugin_$DMG_PLUGIN
  - sudo /var/lib/domogik/domogik_packages/plugin_$DMG_PLUGIN/install_dependencies.sh -pip
  - echo "==== Start zwave emulator"
  - cd ~/py-zwave-emulator/bin
  - ls -l /var/lib/domogik/domogik_packages/plugin_$DMG_PLUGIN/bin
#  - $VIRTUALENV/bin/python zwemulator.py &
  - python zwemulator.py &
  - sudo ~/domogik/src/domogik/tests/travis/travis-start-domogik.sh
script:
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR
  - export PYTHONPATH=/var/lib/domogik
  - dmg_testrunner -a /var/lib/domogik/domogik_packages/plugin_$DMG_PLUGIN/tests/
after_script:
  - ~/domogik/src/domogik/tests/travis/travis-after.sh
  - echo "********** ozwave plugin_test.log *******************"
  - cat /var/log/domogik/plugin_test.log
  - ls -l /var/lib/domogik//domogik_packages/plugin_ozwave/bin
  - echo "********** ozwave Plugin start error *******************"
  - cat /var/log/domogik/ozwave_start_error.log
  - sudo find / -iname ozwave_start_error.log
  - sudo find / -iname plugin_ozwave.log
  - echo "********** ZWave-emulator log *******************"
  - cat ~/py-zwave-emulator/bin/test.log
  - echo "********** Openzwave lib log *******************"
  - cat $TRAVIS_BUILD_DIR/data/OZW_Log.txt

notifications:
  irc: "irc.freenode.net#domogik"
  on_success: never
  on_failure: never
