# This file is used for automated tests with Travis CI : travis-ci.org
# based on the template version 1
# the templates are availables in the documentation on http://docs.domogik.org/domogik/dev/en/package_development/plugins/tests/travis_templates.html
# sudo: false
sudo: required
language: python
python:
  - "2.7"
services:
  - docker
env:
  DMG_BRANCH=testcase_non_xpl
  DMG_PLUGIN=ozwave
  VIRTUALENV=/home/travis/virtualenv/python2.7.10
  DOCKERCMD="docker run -a stdout -a stderr domogik/domogik:develop /bin/sh -c "
  DMG_DIR="/opt/dmg"
before_install:
  - cd ~
  - git clone https://github.com/Nico0084/domogik.git
  - cd domogik
  - git checkout $DMG_BRANCH
  - docker pull domogik/domogik:develop
  - docker run --name domogik_bash -a stdout -p 40404:40404 -p 40406:40406 domogik/domogik:develop
  - docker ps

before_script:
  - docker run -a stdout domogik/domogik:develop /bin/sh -c "cd ~; ls -l; who; echo $TRAVIS_BUILD_DIR; ls -l $TRAVIS_BUILD_DIR; ls -l /opt/dmg"
  - who
  - echo $TRAVIS_BUILD_DIR
  - ls -l $TRAVIS_BUILD_DIR
  - $DOCKERCMD "ls -l /var; ls -l /var/lib/; ls -l /var/lib/domogik; ls -l /var/lib/domogik/domogik_packages"
  - $DOCKERCMD "cd $DMG_DIR; ls -l; ls -l domogik/src/domogik/tests/travis"
  - $DOCKERCMD "ln -s $TRAVIS_BUILD_DIR /var/lib/domogik/domogik_packages/plugin_$DMG_PLUGIN"
  - $DOCKERCMD "ls -l /var/lib/domogik/domogik_packages/plugin_$DMG_PLUGIN/"
  - echo "==== Install zwave emulator dependency"
  - cd ~
  - $DOCKERCMD "cd ~; apt-get install socat"
  - $DOCKERCMD "git clone https://github.com/Nico0084/py-zwave-emulator.git"
  - echo "==== Install Plugin dependency"
  - $DOCKERCMD "cd $TRAVIS_BUILD_DIR; sudo ./install_dependencies.sh -LAST"
  - echo "==== Start zwave emulator"
  - $DOCKERCMD "cd ~/py-zwave-emulator/bin; python zwemulator.py &"
  - docker ps
  - $DOCKERCMD "sudo ~/domogik/src/domogik/tests/travis/travis-start-domogik.sh"
script:
  - echo $TRAVIS_BUILD_DIR
  - cd $TRAVIS_BUILD_DIR
  - export PYTHONPATH=/var/lib/domogik
  - $DOCKERCMD "dmg_testrunner -a /var/lib/domogik/domogik_packages/plugin_$DMG_PLUGIN/tests/"
after_script:
  - ~/domogik/src/domogik/tests/travis/travis-after.sh
  - echo "********** ozwave plugin_test.log *******************"
  - cat /var/log/domogik/plugin_test.log
  - ls -l /var/lib/domogik//domogik_packages/plugin_ozwave/bin
  - echo "********** ozwave Plugin start error *******************"
  - cat /var/log/domogik/ozwave_start_error.log
  - sudo find / -iname ozwave_start_error.log
  - sudo find / -iname plugin_ozwave.log
  - echo "********** ZWave-emulator log *******************"
  - cat ~/py-zwave-emulator/bin/test.log
  - echo "********** Openzwave lib log *******************"
  - cat $TRAVIS_BUILD_DIR/data/OZW_Log.txt

notifications:
  irc: "irc.freenode.net#domogik"
  on_success: never
  on_failure: never
